#!/usr/local/bin/Rscript

# Load libraries required to download from REDCap and install custom packages.
# This loop installs missing pacakges.

for (package in c("REDCapR", "devtools"))
{
  if (!require(package, character.only = TRUE))
  {
    install.packages(package)
    library(package, character.only = TRUE)
  }
}

# Install the custom UdallR library. You may have to change the path, depending
## on where you downloaded UdallR to.
install("~/UdallR", quiet = TRUE)
library(UdallR, quietly = TRUE,  warn.conflicts = FALSE)

today <- gsub("[^0-9]", "", Sys.Date())
outfile <- paste0("closestVisits-", today, ".csv")

# It isn't secure to upload access tokens to GitHub, so store your access token
## in a file like this so R can read it.
rc.token <- readChar("access-token.txt", nchars = 32)

# Read the data from the REDCap API. "stringsAsFactors" stops R from treating
## important strings as factors (which when written to file, are written as the
## underlying numeric representation.
dat <- as.data.frame(redcap_read(redcap_uri = "https://redcap.iths.org/api/",
                                 token = rc.token),
                     stringsAsFactors = FALSE)

# Test the UdallR cleaning function
# The visit variable doesn't do much right now.
cdat <- udallCleanREDCapDataWide(dat, visit = 1)

# Get the closest visits, comparing to the most recent multivis
## UPDATE THIS LINE WHEN NECESSARY
closest.visits  <- getClosestACVisit(cdat,
                                     multivis.df = panuc_multivis_2017_07_17)

# Get the numeric id from the PWAXX-XXXX string
idnum <- gsub("[^0-9]", "", closest.visits$summary_id)

# Add arm name for upload
redcap_event_name <- "visit_for_mri_1_arm_3"

# The columns for upload are just those that are present in both data frames
cols.for.upload <- colnames(closest.visits) %in% colnames(cdat)
closest.visits <- closest.visits[, cols.for.upload]

# Add the idnum and event name first (REDCap is particular)
out <- cbind(idnum, redcap_event_name, closest.visits)

write.csv(out, outfile, row.names = FALSE)
cat(paste(outfile, "saved"), fill = TRUE)
